notifications:
  slack: knot3:bsZjAIfIGf9T5WqUdCUcUsgh
  email:
    recipients:
    - pascal.knodel@student.kit.edu
    - tobias.schulz186@gmail.com
    - daniel.warzel@student.kit.edu
    - gerd.augsburg@student.kit.edu
    - uahih@student.kit.edu
    on_success: always
    on_failure: always
language: c
script:
- git config --global user.name "Knot3 Server"
- git config --global user.email "uaeti@student.kit.edu"
- git remote set-url origin https://github.com/${TRAVIS_REPO_SLUG}.git
- git fetch --unshallow
- git checkout -f ${TRAVIS_BRANCH}
- git checkout -f HEAD
- git submodule update --init --recursive
- sudo apt-get -qq -y install mono-devel mono-dmcs nunit-console libopenal1
- xbuild OggSharp.sln
